kmwtechnology/lucille

lucille-parent/pom.xml
Set surefire configuration redirectTestOutputToFile to false so test output is visible in CI/CD console output.
=> LC-297: Set surefire configuration redirectTestOutputToFile to false.

lucille-core/src/test/java/com/kmwllc/lucille/core/HybridKafkaTest.java
rework test to account for problematic rebalance scenario. the scenario is where on worker commits an offset for a partition that's lower than the offset committed by another worker. This could happen in a rebalance scenario where the first worker loses the partition to the second worker. If the first worker is delayed in committing its final offset for that partition (possibly because the corresponding batch took a long time to index), the first worker's offset could overwrite the second worker's offest. Even though the first worker's offset is lower, it gets committed later in time. This means that the sum of current committed offsets might be lower than the total number of documents processed.
=> LC-303 Attempt to fix intermittent failure in HybridKafkaTest

lucille-core/src/main/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnector.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnectorTest.java, lucille-core/src/test/resources/db-test-end.sql, lucille-core/src/test/resources/db-test-start.sql
**Issue**
Currently, the database connector will silently fail when a Lucille document reserved field (such as id) encounters the same field name (column) in the database it is connecting to.
**Desired Solution**
Skip setting field value if the field name is called id
**Implemented Solution**
- explicit exception for reserved table column names
- introduction of the `ignoreColumns` configuration parameter
=> LC-320 add DatabaseConnector field handling

lucille-core/src/main/java/com/kmwllc/lucille/core/HashMapDocument.java, lucille-core/src/test/java/com/kmwllc/lucille/core/DocumentTest.java
add test and update HashMapDocument.asMap to return shallow copy of internal data so test passes
=> LC-358: add test coverage for Document.asMap()

lucille-core/pom.xml, lucille-core/src/main/java/com/kmwllc/lucille/indexer/OpenSearchIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/util/OpenSearchUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/OpenSearchIndexerTest.java, lucille-core/src/test/resources/OpenSearchIndexerTest/versioning.conf, lucille-parent/pom.xml
LC-335
Changed from RestHighLevelClient to JavaClient for OpenSearch in light of the fact that OpenSearch 3.0.0 will no longer support RestHighLevelClient.
=> Changed existing Rest High Level Client in OpenSearchIndexer to Java Client

lucille-core/src/main/java/com/kmwllc/lucille/stage/AddRandomField.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/AddRandomFieldTest.java
Saw errors due to the randomness of this stage, fixed by changing the range of the values being generated from closed to open. Confirmed no errors by using IntelliJ repeat feature to run all tests for this Stage 10,000+ times
=> LC-372 Fix bug with Intermitten Failures for AddRandomFieldTest

lucille-core/src/main/java/com/kmwllc/lucille/stage/dateformatters/DateYearOnlyFormatter.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/dateformatters/UnixTimestampFormatter.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ParseDateTest.java, lucille-core/src/test/resources/ParseDateTest/config.conf, lucille-plugins/lucille-parquet/src/main/java/com/kmwllc/lucille/parquet/connector/ParquetConnector.java
this improvement does 2 things.
1. it adds a unix timestamp date formatter that can parse a field that contains the milliseconds since the epoch into a date.
2. it tightens up the regular expression that is used for parsing a year.  (we may want to make it even tighter)
=> adding a unix timestamp date formatter

lucille-core/src/main/java/com/kmwllc/lucille/stage/SplitFieldValues.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/SplitFieldValuesTest.java
making split field values operate on all of the values of the input field, not just the first one.
=> LC-389 - support multiple field values in the SplitFieldValues stage.

lucille-core/src/main/java/com/kmwllc/lucille/core/Indexer.java, lucille-core/src/main/java/com/kmwllc/lucille/core/Worker.java, lucille-core/src/main/java/com/kmwllc/lucille/message/HybridIndexerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/HybridWorkerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/IndexerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaIndexerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaWorkerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/LocalMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/PublisherMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/TestMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/WorkerMessenger.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/CSVConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/JSONConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/SequenceConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/SolrConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/VFSConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/XMLConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/PublisherImplTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/RunnerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/CSVIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/ElasticsearchIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/OpenSearchIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/SolrIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/XPathExtractorTest.java, lucille-plugins/lucille-weaviate/src/test/java/com/kmwllc/lucille/weaviate/indexer/WeaviateIndexerTest.java
This PR renames 5 methods as follows:
- WorkerMessenger: sendCompleted() -> sendForIndexing() 
- this is consistent with PublisherMessenger.sendForProcessing()
- IndexerMessenger: pollCompleted() -> pollDocToIndex() 
- this is consistent with WorkerMessenger.pollDocToProcess()
- TestMessenger: getSavedEvents() ->  getSentEvents()
- TestMessenger: getSavedDocumentsSentForProcessing() -> getDocsSentForProcessing()
- TestMessenger: getSavedCompletedDocuments() -> getDocsSentForIndexing()
=> LC-386 Rename methods in Messenger classes for better clarity and consistency

lucille-core/src/main/java/com/kmwllc/lucille/connector/CSVConnector.java
When opencsv throws a CsvException or CsvMalformedLineException we can call getLineNumber() to obtain the physical line number where the error was encountered.
This PR simply updates the CsvConnector's error logging code to include the line number when we can get it.
For the following csv file, the error should reference line 9:
```
a,b,c      # line 1: header
1,2,3      # line 2: valid row
4,5,"      # line 4: beginning of a multi-line row
6"         # line 6: end of multi-line row
7,8,9.     # line 7: valid row
10,11      # line 8: row with too few columns, but still accepted (only generates warning) 
13,14,15"  # line 9: row with unterminated quote -- beginning of problem
16,17
19,20,21
22,23
```
Tests are not included because the only behavior being changed here is log output. We …
=> LC-263 include line number when logging csv processing errors, where possible

lucille-core/src/main/java/com/kmwllc/lucille/stage/ParseDate.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/dateformatters/DateMonthStrFormatter.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/dateformatters/DatePipeFormatter.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/dateformatters/DateTwoYearsFormatter.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/dateformatters/DateYearOnlyFormatter.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/dateformatters/UnixTimestampFormatter.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ParseDateTest.java, lucille-core/src/test/resources/ParseDateTest/config.conf
This PR updates the formatters used in the ParseDate stage so that they always return a ZonedDateTime (as opposed to a LocalDate or LocalDateTime without zone information).
The zone is identified in this order: 1) use the zone info in the date itself, if present and if the format string supports it, 2) use time_zone_id from the stage config, if present, 3) use the system default otherwise.
This PR is against main; however it builds on ideas from https://github.com/kmwtechnology/lucille/pull/70. It goes a bit further to make sure zone information is captured during parsing or as close to parsing as possible, so that there is no room for confusion later.
=> LC-390 use ZonedDateTime in ParseDate instead of LocalDate

lucille-core/src/main/java/com/kmwllc/lucille/core/ConnectorResult.java, lucille-core/src/main/java/com/kmwllc/lucille/core/Publisher.java, lucille-core/src/main/java/com/kmwllc/lucille/core/PublisherImpl.java
This is to prevent overflow issues if 2.1B+ documents are published.
=> LC-392: update counters in publisher to be longs instead of ints

README.md
need to run `mvn clean install` in the example directory
=> LC-398 updated readme instructions for quickstart example

lucille-core/src/main/java/com/kmwllc/lucille/stage/TruncateField.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/TruncateFieldTest.java, lucille-core/src/test/resources/TruncateFieldTest/destination-field.conf, lucille-core/src/test/resources/TruncateFieldTest/destination-not-string.conf, lucille-core/src/test/resources/TruncateFieldTest/in-place.conf, lucille-core/src/test/resources/TruncateFieldTest/max-size-not-int.conf, lucille-core/src/test/resources/TruncateFieldTest/negative-size.conf, lucille-core/src/test/resources/TruncateFieldTest/no-maxSize.conf, lucille-core/src/test/resources/TruncateFieldTest/source-config-not-string.conf
Truncates a string field to a given number of characters. Can be inplace or return the result to a seperate field.
=> LC-281 truncate field stage

lucille-core/src/main/java/com/kmwllc/lucille/stage/ComputeFieldSize.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ComputeFieldSizeTest.java, lucille-core/src/test/resources/ComputeFieldSizeTest/basic.conf, lucille-core/src/test/resources/ComputeFieldSizeTest/no-destination.conf, lucille-core/src/test/resources/ComputeFieldSizeTest/no-output.conf, lucille-core/src/test/resources/ComputeFieldSizeTest/no-source.conf
one of the tests logs an "error accessing bye[] field" but that is intentional. The JsonDocument implementation of Document getBytes() method logs this to notify users that they are incorrectly interpreting a field as a byte[], but allows the program to keep running by returning null.
=> LC-278 ComputeFieldSize stage

lucille-core/src/main/java/com/kmwllc/lucille/core/Indexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/CSVIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/ElasticsearchIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/OpenSearchIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/SolrIndexer.java
This PR removes the duplicated main() methods from some of the Indexer subclasses and places it back on the Indexer base class. The aim is that a user wishing to run Lucille in fully-distributed mode should be able to run com.kmwllc.lucille.core.Indexer at the command line and have the appropriate kind of indexer be started based on the configuration.
Note: We don't yet have test coverage for the main() methods on Indexer, WorkerIndexer, or Worker. I tested this PR manually. The manual test involved starting kafka+zookeeper, starting a lucille Indexer, Worker, and then launching a run via Runner. I confirmed that the run succeeded. In my case, I was using a config file that specified a CSVIndexer. I checked that the csv file that the run should have generated was indeed created and …
=> LC-412 restore ability to start Indexer in fully distributed mode

lucille-core/src/main/java/com/kmwllc/lucille/core/WorkerIndexerPool.java, lucille-core/src/main/java/com/kmwllc/lucille/core/WorkerPool.java, lucille-core/src/test/java/com/kmwllc/lucille/core/WorkerIndexerPoolTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/WorkerPoolTest.java
When starting Worker or WorkerIndexer at the command line, the java process would not terminate if there was an error in certain parts of the config file, including the pipeline section and/or the kafka section. This was happening because at least one thread had been started before attempting to parse those sections of the config. When the parse error was encountered, there was no logic in place to cleanly stop all threads that might have been started. The lingering threads were preventing the process from terminating. This PR addresses that issue by catching exceptions encountered while starting Worker and WorkerIndexer threads and, in case an exception is encountered, calling stop() on the corresponding thread pool.
Update: after a closer look, it turned out the issue with WorkerIndexer …
=> LC-399 make sure Worker and WorkerIndexer terminate when a startup exception is encountered

lucille-core/src/main/java/com/kmwllc/lucille/stage/ParseFloats.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ParseFloatsTest.java, lucille-core/src/test/resources/ParseFloatsTest/bad.conf, lucille-core/src/test/resources/ParseFloatsTest/basic.conf, lucille-core/src/test/resources/ParseFloatsTest/dest.conf
one "bug" I found was that the stage would throw an exception if the input string could not correctly be parsed to a float list. Since the design philosophy of lucille is to ingest as many documents as possible without crashing, I changed this to just log a warning and skip the document instead. 
NOTE: the stage currently will consider the empty list ("[]") as non-parsable and skip rather than treating it as an empty list of floats and removing the field. Let me know if I should change this behavior. 
FIXED ABOVE: the stage now will parse the empty list and since its behavior is to remove the source field and replace it, it effectively just deletes the source field since there is no way to add an empty list.
=> LC-419 added tests for ParseFloats stage

lucille-core/src/main/java/com/kmwllc/lucille/core/KafkaDocument.java, lucille-core/src/test/java/com/kmwllc/lucille/core/KafkaDocumentTest.java
The aim of this PR is to expand test coverage and code documentation for KafkaDocument, KafkaDocumentSerializer, and KafkaDocumentDeserializer.
The test for the KafkaDocument serde (serializer/deserializer pair) was originally written in an earlier PR for HashMapDocument (https://github.com/kmwtechnology/lucille/pull/9/files) but that PR is dormant. In writing the serde test, another gap was noticed and filled re: basic tests for getters/setters on KafkaDocument.
=> LC-430 expand test coverage for KafkaDocument

lucille-core/src/main/java/com/kmwllc/lucille/core/ZKRetryCounter.java, lucille-core/src/test/java/com/kmwllc/lucille/core/ZKRetryCounterTest.java, lucille-core/src/test/resources/ZKRetryCounterTest/config.conf, lucille-core/src/test/resources/ZKRetryCounterTest/retry10.conf
found one "bug" which is not really a functional bug but seems to be unintended behavior.
for non-kafka documents, the "counterPath" which is generated has two backslashes in it rather than one (check line 116 of the tests). It seems as though this is supposed to be a path-like representation in which case the double backslash would not typically be intended.
=> LC-423 added tests for ZKRetryCounter

lucille-core/pom.xml, lucille-core/src/test/java/com/kmwllc/lucille/util/SolrUtilsTest.java, lucille-core/src/test/resources/db-test-start.sql, lucille-parent/pom.xml, lucille-plugins/lucille-ocr/pom.xml
After the 0.2.0 release, we found some vulnerable dependencies in Lucille. Here we are upgrading the following:
- org.apache.kafka/kafka-clients
- com.google.guava/guava
- com.jayway.jsonpath/json-path
- net.mguenther.kafka/kafka-junit
- com.h2database/h2 (updated test for new version)
- com.fasterxml.jackson.core/jackson-annotations, jackson-databind, jackson-core
- com.fasterxml.jackson.datatype/jackson-datatype-jsr310
- org.apache.solr/solr-test-framework, solr-solrj, solr-solrj-zookeeper, solr-solrj-streaming, solr-core
- com.google.protobuf/protobuf-bom
- io.netty/netty-bom
- org.apache.pdfbox/pdfbox
The vulnerable dependencies are listed in the ticket: https://kmwllc.atlassian.net/browse/LC-406
=> LC-406 - Upgrade vulnerable Lucille dependencies.

lucille-examples/lucille-distributed-example/pom.xml
the wrong version of lucille was used in the distributed mode example which caused a build error in github actions
=> fix to pom which was breaking github action

lucille-core/src/main/java/com/kmwllc/lucille/core/Condition.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ConfigValidationTest.java, lucille-core/src/test/resources/ConfigValidationTest/conditions-optional-wrong.conf, lucille-core/src/test/resources/StageTest/multipleConditions.conf
The Conditions constructor now requires the provided operator to be valid and throws a runtime exception otherwise. Since the condition object is created at validation time (before a run) this validates the conditions clauses "statically"
=> LC-462: stage conditions paradigm asserts that provided operator is valid

.github/workflows/release-to-sonatype.yml
Allows release version to be set when kicked off by release creation.
=> LC-457 - set version for release-to-sonatype github action when creating new release 

lucille-core/src/main/java/com/kmwllc/lucille/stage/ParseJson.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ParseJsonTest.java
ParseJson currently deletes the src field after parsing the json contained in it. If a user wants to remove src, they can do it with a DeleteFields stage. This PR updates ParseJson so it leaves the src field in place. This leaves the choice up to the user re: whether to delete src later via DeleteFields.
=> LC-479 ParseJson stage should not delete the src field

lucille-core/src/main/java/com/kmwllc/lucille/core/Document.java, lucille-core/src/main/java/com/kmwllc/lucille/core/HashMapDocument.java, lucille-core/src/main/java/com/kmwllc/lucille/core/JsonDocument.java, lucille-core/src/test/java/com/kmwllc/lucille/core/DocumentTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/JsonDocumentTest.java
The Document interface has a single-value json setter, but not corresponding getters or updaters.
There's `void setField(String name, JsonNode value)` but no corresponding `JsonNode getJson(String name)`
This PR fleshes out Document's support for JSON values by adding the standard getters and updaters.
The complication with Json values is that JsonDocument internally stores multivalued fields as JsonArrays. For example, if you add 1, 2, 3, 4 to a multivalued int field, JsonDocument will represent this as a JsonArray containing those ints. But what should happen if someone _adds_ a JsonArray containing ints 1, 2, 3,4 via setField(String name, JsonNode value)? Should JsonDocument treat this as a multivalued field containing 4 ints, or should it treat this as a single-valued field containing …
=> LC-314: add Document support for JSON getters and setters

lucille-core/bin/lucille.sh
[LC-472](https://kmwllc.atlassian.net/browse/LC-472): The lucille.sh script no longer works properly so we just want to remove to from the codebase for now. In the future, there may be some benefit to adding another script to show how you could configure a run.
=> LC-472 - Remove lucille.sh.

lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/message/KafkaUtilsTest.java, lucille-examples/lucille-distributed-example/conf/main.conf, lucille-examples/lucille-distributed-example/pom.xml, lucille-examples/lucille-distributed-example/src/test/java/com/kmwllc/lucille/distributed/DistributedIT.java
uses profiles so that the test can be conditionally initiated from the lucille-distributed-example. Running 
```mvn verify -Pnightly``` starts the test. NOTE: must have docker desktop running and make sure to delete all containers volumes in subsequent runs.
KafkfaUtils has to be modified to avoid a TopicAlreadyExistsException. This fixes the issue but may not be the fix we want so this should be reviewed in more detail
=> LC-482: dockerized distributed test attached to maven verify

lucille-parent/pom.xml
Upgraded to [OpenSearch Java Client 2.11.1](https://github.com/opensearch-project/opensearch-build/blob/main/release-notes/opensearch-release-notes-2.11.1.md) that uses improved [HttpClient 5.3](https://github.com/apache/httpcomponents-client/blob/rel/v5.3.1/RELEASE_NOTES.txt) to fix a **HttpClient** bug ([HTTPCLIENT-2219 Bug](https://issues.apache.org/jira/browse/HTTPCLIENT-2219)) that arises when run within a Kubernetes container.
Older **HttpClient** versions throw odd errors from inside of Kubernetes containers  that were fixed in later versions: 
**Error from older HttpClient that works fine elsewhere but throws an error when run in Kubernetes container**:
```
org.apache.hc.core5.http.ParseException: Invalid protocol version; error at offset 0: …
```
=> Fix: Upgrade OpenSearch Java to 2.8.2 for HttpClient 5.3 Updates

lucille-core/src/main/java/com/kmwllc/lucille/util/FileUtils.java, lucille-plugins/lucille-tika/src/main/java/com/kmwllc/lucille/tika/stage/TextExtractor.java, lucille-plugins/lucille-tika/src/test/java/com/kmwllc/lucille/tika/stage/TextExtractorTest.java, lucille-plugins/lucille-tika/src/test/resources/TextExtractorTest/getFileInputStream.conf
- closing of inputStream is in a separate branch LC-528. This branch changes how it got inputStream from filepath
- changed test for TextExtractor to use absolute path rather than relative path to reflect the same procedure. (doc.getString(filePathField) would return an absolute path)
=> LC-532: fix leak of threads in TextExtractor stage

lucille-parent/pom.xml
Resolves CVEs in `amazon-ion` and `vfs-s3 by upgrading to the latest versions.
NOTE: `amazon-ion` is no longer being imported, since we have upgraded to `aws-java-sdk` version 1.12.769 which does not depend on ion.
Tickets: 
https://kmwllc.atlassian.net/browse/LC-525
https://kmwllc.atlassian.net/browse/LC-531
CVES:
https://nvd.nist.gov/vuln/detail/CVE-2024-21634
https://mvnrepository.com/artifact/com.github.abashev/vfs-s3/4.3.6
=> LC-525 increase version of vfs and aws-sdk to the latest to fix CVEs

lucille-core/pom.xml, lucille-examples/lucille-distributed-example/pom.xml, lucille-examples/lucille-opensearch-ingest-example/pom.xml, lucille-parent/pom.xml
There is a vulnerability with junit 4.13: [CVE -CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250)
We are upgrading to junit 4.13.2 to fix this and it includes need for upgrading junit 5 because bug in junit 5.6.2 that doesn't support junit 4.13.2 (only 4.12 and 4.13).
=> LC-544 - Upgrade junit 4.13 to 4.13.2

lucille-core/src/main/java/com/kmwllc/lucille/indexer/SolrDocRequests.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/SolrIndexer.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/SolrIndexerTest.java, lucille-core/src/test/resources/SolrIndexerTest/ignoreId.conf
- now allows user to place "id" field in ignoreFields config.
- ignoreFields will now apply to Children and Parent Document(s)
- Changed SolrInputRequest to use SolrId instead of Document.ID_FIELD
=> LC-535: added ability to ignore "id" field in SolrIndexer

lucille-plugins/lucille-pinecone/pom.xml, lucille-plugins/lucille-pinecone/src/main/java/com/kmwllc/lucille/pinecone/indexer/PineconeIndexer.java, lucille-plugins/lucille-pinecone/src/test/java/com/kmwllc/lucille/pinecone/indexer/PineconeIndexerTest.java, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/empty-namespaces-update.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/empty-namespaces.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/failure-config.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/good-config.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/no-namespaces-update.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/no-namespaces.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/shutdown-config.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/two-namespaces-update.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/two-namespaces.conf
- updated Pinecone to 2.0.0, making use of their serverless offerings
- providing environment is only for pod-based indexes, and api key is now project specific.
- moving from pod based to serverless https://docs.pinecone.io/guides/indexes/migrate-a-pod-based-index-to-serverless
- https://docs.pinecone.io/guides/get-started/key-concepts
=> LC-505: Update PineconeIndexer

application-example.conf, lucille-core/src/main/java/com/kmwllc/lucille/core/ConnectorThread.java, lucille-core/src/main/java/com/kmwllc/lucille/core/Runner.java, lucille-core/src/main/java/com/kmwllc/lucille/core/Worker.java, lucille-core/src/main/java/com/kmwllc/lucille/core/WorkerIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/core/WorkerPool.java, lucille-core/src/main/java/com/kmwllc/lucille/core/WorkerThread.java, lucille-core/src/main/java/com/kmwllc/lucille/util/ThreadNameUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/core/HeartbeatTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/RunnerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/WorkerIndexerPoolTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/WorkerPoolTest.java, lucille-core/src/test/resources/WorkerPoolTest/watcher.conf
- created ThreadNameUtils class for naming/catching Lucille threads
- all Lucille threads are now created with prefix “Lucille”
- unified logTimer and heartbeat logs to a single Timer thread, which is scheduled using a executorService to watch every 5 seconds
- each time workerPool logs, a heartbeat is also logged.
=> LC-487: fix transient worker test

application-example.conf, lucille-parent/pom.xml, lucille-plugins/lucille-pinecone/src/main/java/com/kmwllc/lucille/pinecone/indexer/PineconeIndexer.java, lucille-plugins/lucille-pinecone/src/test/java/com/kmwllc/lucille/pinecone/indexer/PineconeIndexerTest.java, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/deletion-config-with-prefix.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/deletion-config.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/update-and-delete.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/upsert-and-delete-prefix.conf, lucille-plugins/lucille-pinecone/src/test/resources/PineconeIndexerTest/upsert-and-delete.conf
- added support for deletion using Indexer config deletionMarkerField & deletionMarkerFieldValue
- namespace will now be "default" if no namespaces defined (deletion by prefix needs non empty namespace)
- added additional checks on other operations to increase robustness
- upgraded netty & grpc to latest version to avoid error in internal grpc calls
- added javadocs
- added local testing
=> LC-506: support deletion for PineconeIndexer

lucille-core/src/main/java/com/kmwllc/lucille/util/ElasticsearchUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/util/ElasticsearchUtilsTest.java
This ticket has not been completed as mockito currently does not allow for argument capture for static methods. The tests can still be made using mockito's ```mockStatic``` method but it will most likely be less precise.
=> LC-422: ElasticsearchUtilsTest

lucille-core/src/main/java/com/kmwllc/lucille/stage/QueryDatabase.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/QueryDatabaseTest.java
Noticed that publishing process would fail when trying to merge PRs to main, even though the PRs themselves pass the build process. Went through the logs and found that DatabaseConnectorTests in publishing process is failing due to detecting more than one session to the test database. Found out that Stage QueryDatabase tests were not explicitly closing connection. Found out that QueryDatabaseTests ran first before DatabaseConnectorTests ran in publishing process, while the DatabaseConnectorTests ran before QueryDatabaseTest in the building process, which explains why one was passing while the other was failing. Also found out that QueryDatabase was creating unnecessary connections.
Things changed:
- fix QueryDatabase to break out of connection retry loop once a single connection has been …
=> LC-557: investigate bug causing publishing failures

lucille-core/src/main/java/com/kmwllc/lucille/stage/AddRandomField.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/AddRandomFieldTest.java, lucille-core/src/test/resources/AddRandomFieldTest/concatenate.conf, lucille-core/src/test/resources/AddRandomFieldTest/nofilepath.conf
This PR includes several improvements to the AddRandomFields stage:
1) a "concatenate" mode now allows for multiple random values to be set as a single space-separated string instead of as multiple field values. i.e. "14 34 323 54" vs. ["14", "34", "323", "54"]
2) when selecting random values from an integer range, the stage no longer generates a list of all integers in the range
3) when reading data from a file, the stage no longer attempts to uniquify the contents (which can be very time consuming for a large file)
=> LC-582/LC-583 improve AddRandomFields stage

lucille-core/src/main/java/com/kmwllc/lucille/util/SolrUtils.java
this will set the system property so the solrj client ignores hostname / cert ssl validation
=> LC-595 - supporting the config for solr.acceptInvalidCert for the solr indexer 

lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/AzureStorageClient.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/LocalStorageClient.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/S3StorageClient.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/FileConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/storageclient/LocalStorageClientTest.java
Publishing has failed for LC-144 even though the Maven built process passed. Taking a look at the publishing, some of the test are failing even though the maven build is passing. Took a deeper look and it seems like Files.walk(startingDirectory) in LocalStorageClient does not guarantee ordering of the files, causing assertion to fail. Instead, we should use Files.walk(startingDirectory).sorted() to produce a stream in the natural order. This PR is to correct that and make sure that we get repeatable results
=> LC-144: enhance FileConnector

lucille-examples/lucille-distributed-example/src/test/java/com/kmwllc/lucille/distributed/VerifyIngestResult.java
`VerifyIngestResult` now expects absolute paths in the ingested document's "source" field. 
Change was needed as part of the changes in LC-144... here's my understanding of what necessitated this:
- Previously, `CSVConnector` was extracting a path String from `config`.
- In `execute`, it set `filePathField` to this extracted path String.
- Now, this functionality takes place in `CSVFileHandler`.
- Its `getDocumentFromLine` method sets `filePathField` to one of its arguments - which instead appears to be a String generated from a `Path` object's `toAbsolutePath()` output.
This appears to be the behavior with other file types, so I'm guessing this is the intended behavior moving forward?
=> LC-599: Fix Nightly Smoketest

lucille-examples/lucille-joining-db-connector-example/pom.xml, lucille-parent/pom.xml, lucille-plugins/lucille-parquet/pom.xml
[CVE-2024-23454](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-23454) : hadoop-common 
[CVE-2024-7254](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-7254) : protobuf-bom
[CVE-2024-47535](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-47535): netty-bom 
[CVE-2023-22102](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-22102): mysql-connector-java > mysql-connector-j
=> LC-564 - upgrade packages for CVEs 

lucille-core/src/test/java/com/kmwllc/lucille/indexer/CSVIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/ElasticsearchIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/OpenSearchIndexerTest.java, lucille-core/src/test/resources/CSVIndexerTest/includeHeader.conf, lucille-core/src/test/resources/CSVIndexerTest/invalidConfig.conf, lucille-core/src/test/resources/CSVIndexerTest/missingParentConfig.conf, lucille-core/src/test/resources/ElasticsearchIndexerTest/invalidConfig.conf, lucille-core/src/test/resources/ElasticsearchIndexerTest/routingAndUpdate.conf, lucille-core/src/test/resources/ElasticsearchIndexerTest/updateConfig.conf, lucille-core/src/test/resources/ElasticsearchIndexerTest/versioningUpdate.conf, lucille-core/src/test/resources/OpenSearchIndexerTest/invalidConfig.conf, lucille-core/src/test/resources/OpenSearchIndexerTest/routingAndUpdate.conf, lucille-core/src/test/resources/OpenSearchIndexerTest/updateConfig.conf, lucille-core/src/test/resources/OpenSearchIndexerTest/versioningUpdate.conf
ElasticsearchIndexer: 66% / 57% → 99% / 87%
OpensearchIndexer: 74% / 64% → 92% / 81%
CSVIndexer: 72% / 54% → 92% / 95%
=> LC-426: Improved Unit Tests for CSV/Open/Elasticsearch Indexers

lucille-core/src/main/java/com/kmwllc/lucille/connector/FileConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/BaseStorageClient.java, lucille-core/src/main/java/com/kmwllc/lucille/core/fileHandler/CSVFileHandler.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/FileConnectorTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/storageclient/AzureStorageClientTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/storageclient/GoogleStorageClientTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/storageclient/LocalStorageClientTest.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/storageclient/S3StorageClientTest.java
Now we have a different character for when we are handling zip / tar files. This just was a small change in `BaseStorageClient` as well as a minor update for `CSVFileHandler` because of how it was assigning IDs to documents.
=> LC-618: Special path separator for archive files

lucille-core/src/main/java/com/kmwllc/lucille/core/Runner.java, lucille-core/src/main/java/com/kmwllc/lucille/core/Worker.java, lucille-core/src/main/java/com/kmwllc/lucille/core/WorkerPool.java, lucille-core/src/main/java/com/kmwllc/lucille/util/ThreadNameUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/core/HeartbeatTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/WorkerPoolTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/WorkerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/util/ThreadNameUtilsTest.java
Connector threads always get the runID. We only attach them to Worker/Indexer threads in local runs. Many of the "localRunID" changes/plumbing are mirrored in LC-608,
=> LC-627: Run IDs in Thread Names

lucille-examples/lucille-distributed-example/src/test/java/com/kmwllc/lucille/distributed/VerifyIngestResult.java
In the event of a test failure, it'll be a bit clearer which field caused the assertion to fail - so we can see it directly from the nightly smoketest and won't have to replicate locally by running the example and then running docker compose up, to gain access to Solr.
=> LC-643: More rigid VerifyIngestResult assertions

lucille-core/pom.xml, lucille-core/src/test/java/com/kmwllc/lucille/core/HybridKafkaTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/KafkaTest.java, lucille-core/src/test/resources/HybridKafkaTest/childrenConfig.conf, lucille-core/src/test/resources/HybridKafkaTest/childrenConfigWithEvents.conf, lucille-core/src/test/resources/HybridKafkaTest/customDeserializer.conf, lucille-core/src/test/resources/HybridKafkaTest/eventTopic.conf, lucille-core/src/test/resources/HybridKafkaTest/noopConfig.conf, lucille-core/src/test/resources/HybridKafkaTest/poolConfig.conf, lucille-core/src/test/resources/HybridKafkaTest/sourceTopicWildcard.conf, lucille-core/src/test/resources/KafkaTest/twoConnectors.conf, lucille-parent/pom.xml, lucille-plugins/lucille-pinecone/src/test/java/com/kmwllc/lucille/pinecone/stage/EmitDocsToDeleteByPrefixTest.java
Replaces the old dependency with some Kafka related libraries from Spring. This decreases the runtime of `HybridKafkaTest` from ~82 seconds to ~55.5 seconds, a ~26-27 second decrease. This decreases the runtime of `KafkaTest` from ~40 sec to ~20.5 sec, a ~19 second decrease.
Both use an `@ClassRule`, meaning there is one embedded instance of Kafka created for each test class. As such, for `HybridKafkaTest`, each test is using different topic names. We save ~10 seconds in runtime by only using one, class-level instance of EmbeddedKafka.
Kafka is brought up to `3.8.1`.  The Spring libraries are on version `3.3.3`. (Spring-Kafka versions don't match Kafka versions. These are compatible versions.). Kafka `3.9.0` is available, but it doesn't play nicely with the Spring libraries, which are …
=> LC-644: Replace KafkaJUnit

lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaUtils.java, lucille-core/src/test/resources/HybridKafkaTest/sourceTopicWildcard.conf
With these changes, `testSourceTopicWildcard` runs ~25 seconds faster than before. In total, `HybridKafkaTest` only takes ~28 seconds now!
The culprit here was the call to `waitUnique` the second time in the test. It was taking _forever_ for the documents to actually show up to be indexed. My rudimentary understanding is that Kafka wasn't recognizing the new topics until a certain timeout interval, since I noticed the time it took for the documents to get polled was ~30 seconds - seemed like some sort of default / set timeout value to me. I went digging and found that `metadata.max.age.ms` could speed this up - so I made it possible to set this in a Config that is passed to `KafkaUtils.createConsumerProps`, and set it to `5000` in the test's Config. I found that if you set this too low …
=> LC-651: Improve HybridKafkaTest

lucille-core/src/main/java/com/kmwllc/lucille/core/Indexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/CSVIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/ElasticsearchIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/NopIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/OpenSearchIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/SolrIndexer.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/ElasticsearchIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/OpenSearchIndexerTest.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/SolrIndexerTest.java, lucille-plugins/lucille-pinecone/src/main/java/com/kmwllc/lucille/pinecone/indexer/PineconeIndexer.java, lucille-plugins/lucille-weaviate/src/main/java/com/kmwllc/lucille/weaviate/indexer/WeaviateIndexer.java, lucille-plugins/lucille-weaviate/src/test/java/com/kmwllc/lucille/weaviate/indexer/WeaviateIndexerTest.java
using some existing POC-style changes, `Indexer.sendToIndex` now returns a `Set<Document>` representing the Documents that were _not_ successfully indexed. Exceptions are only thrown in more exceptional circumstances now. 
Internally, the Indexers maintain a `Map<String, Document>` to easily retrieve the specific Documents that failed based on the IDs returned by the errors (which will be a DocID / ID Override value).
One note w.r.t. the ID Override is that there isn't support for multiple documents with the same ID Override value. I'm not sure if this is an allowed / supported behavior. We could use a List to mitigate this, it would just cause a bit of overhead.
=> LC-666: Specific Indexer Failures for Solr, Open, and Elastic

lucille-core/pom.xml, lucille-parent/pom.xml
We are using the AWS S3 S3Client to connect to S3 buckets. With the S3Client, we are using the [Default Credentials Provider](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials-chain.html). For the third provider in the chain, `WebIdentityTokenFileCredentialsProvider`, the `software.amazon.awssdk:sts` dependency must be included in the classpath. Rather than making the user include that dependency in their own pom, we are adding it here.
Additionally, I have just extracted out the aws sdk versions since there are 4 with the same version of 2.29.1.
=> LC-667: Add sts dependency for WebIdentityTokenFileCredentialsProvider

lucille-plugins/lucille-parquet/pom.xml
Upgrade org.apache.parquet:parquet-avro from 1.15.0 to 1.15.1.
[NVD - CVE-2025-30065](https://nvd.nist.gov/vuln/detail/CVE-2025-30065)
=> LC-674 - Upgrade parquet-avro for CVE

lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/AzureStorageClient.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/BaseFileReference.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/BaseStorageClient.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/FileReference.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/GoogleStorageClient.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/LocalStorageClient.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/storageclient/S3StorageClient.java
Hold more properties in the `BaseFileReference`, expose a direct way to get file contents, allowing `asDoc` methods to be reused in `BaseFileReference`. Renamed `asDoc` to `decompressedFileAsDoc` to be a bit clearer on the use of the method.
Use a special method for `getFileContent`, returning a `byte[]`, instead of `getContentStream` to avoid 
1. Having to throw an IOException 
2. The overhead associated with opening an InputStream just to immediately exhaust it
instead of just reading the `InputStream` from `getContentStream` which was already available.
=> LC-661: Small FileReference Refactor

lucille-core/src/main/java/com/kmwllc/lucille/connector/AbstractConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/CSVConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/FileConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/JSONConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/SequenceConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/SolrConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/connector/xml/XMLConnector.java
The `ParquetConnector` isn't included... I have some JavaDocs for it in the refactor PR.
=> LC-569: Improved JavaDocs on Connectors

lucille-core/src/main/java/com/kmwllc/lucille/stage/ParseJson.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ParseJsonTest.java
When a Document is missing the source field, `this.jsonParseCtx.parse` throws an `IllegalArgumentException`. Now we just catch it and reference the Document's in a `StageException`. This makes the Stage's `Exception` a bit clearer when child documents are in play.
=> LC-551: Improved Exception Handling in ParseJson

lucille-core/src/main/java/com/kmwllc/lucille/stage/DictionaryLookup.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/QueryOpensearch.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/util/DictionaryManager.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/util/DictionaryManagerTest.java
1. `DictionaryManager` / "dictionaries" in general use a `List<String>` instead of `String[]` to prevent the contents from being modified.
2. `QueryOpensearch` has a shared `HttpClient` to improve its scalability. (This is in line with the recommended usage of `HttpClient`, evidently. It is thread safe.) The issue here would be running a Pipeline that uses `QueryOpensearch` - potentially multiple times - either on multiple threads or in multiple concurrent runs. Each instance of the Stage in each Thread/Run will open an HTTPClient, and since this is done _at the same time_, it'll cause issues.
=> LC-545: Safe Singletons 

lucille-core/src/main/java/com/kmwllc/lucille/stage/Print.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/PrintTest.java
- JavaDocs warning about the importance of `appendThreadName` in a multithreaded run
- `appendThreadName` defaults to `true`
=> LC-498: Print "AppendThreadNames" follow-up

lucille-core/src/main/java/com/kmwllc/lucille/core/Document.java, lucille-core/src/main/java/com/kmwllc/lucille/core/HashMapDocument.java, lucille-core/src/main/java/com/kmwllc/lucille/core/JsonDocument.java, lucille-core/src/test/java/com/kmwllc/lucille/core/JsonDocumentTest.java
`ObjectNode` uses a `LinkedHashMap` internally, so we can preserve the ordering by using a `LinkedHashSet` in `getFieldNames`. I added the same behavior to `HashMapDocument` just in case...
=> LC-691: Document.getFieldNames Preserves Insertion Order

lucille-core/pom.xml, lucille-core/src/main/java/com/kmwllc/lucille/stage/PromptOllama.java
Just a few things to enhance with Ollama I noticed while using it in an actual pipeline.
1. Updated the Ollama4j version
2. System prompt is optional, since you may be using a model with a System prompt "built into" it (Modelfile)
3. Sets `format: "json"` in the API request, preventing errors with the LLM outputting JSON in Markdown + preventing parsing the response
4. Retrieving the timeout correctly - casting error took place using `ConfigUtils.getOrDefault`. 
5. Putting a warning about potentially increasing the timeout if you have a multithreaded Pipeline
I have some stashed changes that use the `generate` endpoint instead of the `chat` endpoint which creates more reliable results, especially when lots of Documents are in the pipeline. But we do run into an issue with the formatting …
=> Minor Ollama Enhancements

lucille-core/src/main/java/com/kmwllc/lucille/stage/DictionaryLookup.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/DictionaryLookupTest.java, lucille-core/src/test/resources/DictionaryLookupTest/set_config_any_match.conf
When you use `set_only`, you can control whether it uses any or all matching with the optional `use_any_match` parameter. It defaults to `false`, so existing configs will not be changed.
=> LC-702: Support "Any Matching" in DictionaryLookup

lucille-examples/lucille-distributed-example/conf/main.conf, lucille-examples/lucille-file-to-file-example/conf/csv-connector.conf, lucille-examples/lucille-file-to-file-example/conf/json-connector.conf, lucille-examples/lucille-simple-csv-solr-example/conf/simple-csv-solr-example.conf, lucille-examples/lucille-vector-ingest-example/conf/10M-parquet-pinecone.conf
Since we merged in a lot of tickets - which included a lot of changes, especially to the FileConnector - some of the configs in lucille-example are technically invalid, but sneak through the ConfigValidationTest. For example, in the simple CSV Solr example:
```hocon
{
class: "com.kmwllc.lucille.connector.FileConnector",
pathsToStorage: ["conf/songs.csv"],
name: "connector1",
pipeline: "pipeline1"
fileOptions: {
csv: { }
}
}
```
This PR updates the FileConnector configs in the `lucille-examples`
=> LC-705: Update FileConnector Configs in lucille-example

lucille-core/src/main/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnector.java
* These two parameters have different capitalization between the Spec and the Config value getters, making it impossible to set these values currently
* This is impacting a customer and has been temporarily resolved via use of a Custom Connector. However, we should revert that change after this PR has been released.
=> LC-709 fix capitalization of preSQL and postSQL

README.md
Added a new line under the 'More Information' section of the top level README to point users towards the documentation website.
=> LC-710: Update top level README to link to documentation website

lucille-core/pom.xml, lucille-parent/pom.xml
Upgraded the elasticsearch version to 8.18.4 and removed the elasticsearch-rest-high-level-client dependency.
=> LC-717: Upgraded elasticsearch-java version to 8.18.4, removed rest-high-level-client

lucille-core/src/main/java/com/kmwllc/lucille/core/fileHandler/JsonFileHandler.java, lucille-core/src/test/java/com/kmwllc/lucille/core/fileHandler/JsonFileHandlerTest.java, lucille-core/src/test/resources/FileHandlerTest/JsonFileHandlerTest/noids.jsonl
Added functionality to JsonFileHandler to declare a single or composite id field and an id format similar to that of CsvFileHandler.
=> LC-719: JsonFileHandler Id Fields
