kmwtechnology/lucille

lucille-core/src/main/java/com/kmwllc/lucille/core/HashMapDocument.java, lucille-core/src/main/java/com/kmwllc/lucille/util/LinkedMultiMap.java, lucille-core/src/main/java/com/kmwllc/lucille/util/MultiMap.java, lucille-core/src/test/java/com/kmwllc/lucille/core/HashMapDocumentTest.java, lucille-core/src/test/java/com/kmwllc/lucille/util/LinkedMultiMapTest.java
convert LinkedMultiMap to using a single internal map
begin fleshing out HashMapDocument serialization
=> convert LinkedMultiMap to using a single internal map

lucille-plugins/lucille-parquet/src/main/java/com/kmwllc/lucille/parquet/connector/ParquetConnector.java
When parsing the parquet files, the documents are built before the skip parameter is checked, resulting in unnecessary computation. The solution will be to check the number of documents in the retrieved group of rows and skip processing them if the current count is lower than the skip parameter.
Verified that it works on a vm and time to publish the first document after skipping 5,196,134 reduced from 1,853 s to 55 s
=> ParquetConnector: add document skipping based on start parameter

lucille-core/src/main/java/com/kmwllc/lucille/util/StageUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/util/StageUtilsTest.java
Found that the StageUtils.java class under utils in lucille-core was missing tests. This is not the only utils class missing tests, but created a draft of how tests might look like for these classes.
=> LC-321 Created tests for StageUtils class

lucille-core/src/main/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnector.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnectorTest.java, lucille-core/src/test/resources/db-test-end.sql, lucille-core/src/test/resources/db-test-start.sql
cosmetic clean-up for DatabaseConnector
=> LC-322 DatabaseConnector cleanup

lucille-core/src/main/java/com/kmwllc/lucille/connector/VFSConnector.java, lucille-core/src/test/java/com/kmwllc/lucille/connector/VFSConnectorTest.java
=> Removal of byte64 encoding of file content in VFSConnector and related test changes

lucille-core/pom.xml
https://kmwllc.atlassian.net/browse/LC-347
=> LC-347 fix dependency conflict that prevents lucille run

lucille-core/src/main/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnector.java
LC-316
Cleans up the connection by moving the code into a finally block
=> LC-316 Cleaned up connection for result sets in database connector

lucille-core/src/main/java/com/kmwllc/lucille/stage/AddRandomField.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/AddRandomFieldTest.java, lucille-core/src/test/resources/AddRandomFieldTest/basicfilepath.conf, lucille-core/src/test/resources/AddRandomFieldTest/foods.txt, lucille-core/src/test/resources/AddRandomFieldTest/nofilepath.conf
Created a new stage that adds random data to a document
=> LC-361 addrandomfield stage

lucille-core/src/main/java/com/kmwllc/lucille/indexer/ElasticsearchIndexer.java, lucille-core/src/test/java/com/kmwllc/lucille/indexer/ElasticsearchIndexerTest.java
Added bulk response handling and relevant test for ElasticsearchIndexer
=> LC-369 Bulk Response Handling ElasticsearchIndexer

application-example.conf, lucille-core/src/main/java/com/kmwllc/lucille/core/ConfigUtils.java, lucille-core/src/main/java/com/kmwllc/lucille/core/Worker.java, lucille-core/src/main/java/com/kmwllc/lucille/core/WorkerIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/ElasticsearchIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/OpenSearchIndexer.java, lucille-core/src/main/java/com/kmwllc/lucille/indexer/SolrIndexer.java
Reorganized application-example.conf and went through all mentions of config properties for Lucille items other than stages and plug-ins. There is definitely more to be added from reviewers and some unknown properties that need to be questioned / resolved.
=> LC-338 application-example.conf documentation

lucille-core/src/main/java/com/kmwllc/lucille/indexer/SolrIndexer.java
Missing import for SolrJ upgrade PR
=> LC-379 Fix missing import for upgrade SolrJ 

lucille-core/src/test/java/com/kmwllc/lucille/stage/RandomVectorTest.java, lucille-core/src/test/resources/RandomVectorTest/append.conf, lucille-core/src/test/resources/RandomVectorTest/default.conf, lucille-core/src/test/resources/RandomVectorTest/four.conf, lucille-core/src/test/resources/RandomVectorTest/more_dest.conf, lucille-core/src/test/resources/RandomVectorTest/noDimensions.conf, lucille-core/src/test/resources/RandomVectorTest/noField.conf, lucille-core/src/test/resources/RandomVectorTest/overwrite.conf, lucille-core/src/test/resources/RandomVectorTest/skip.conf
this stage did not have any tests as per the jacaco code coverage reports
=> LC-420 added unit tests to RandomVector stage

lucille-core/src/main/java/com/kmwllc/lucille/core/Worker.java, lucille-core/src/main/java/com/kmwllc/lucille/message/HybridWorkerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaIndexerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaPublisherMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaUtils.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaWorkerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/LocalMessenger.java, lucille-core/src/test/java/com/kmwllc/lucille/message/KafkaUtilsTest.java
https://kmwllc.atlassian.net/browse/LC-415
=> LC-415 when creating kafka event topic, don't fail if it already exists

lucille-examples/lucille-distributed-example/pom.xml
=> LC-352: fixed build warning

lucille-core/src/test/java/com/kmwllc/lucille/indexer/IndexerFactoryTest.java, lucille-core/src/test/resources/IndexerFactoryTest/config_valid_type_csv.conf, lucille-core/src/test/resources/IndexerFactoryTest/config_valid_type_elastic.conf, lucille-core/src/test/resources/IndexerFactoryTest/config_valid_type_open.conf
new PR since the previous one included tests from another PR
=> LC-427: improved indexer factory tests

lucille-core/src/test/java/com/kmwllc/lucille/core/FileToFileIngestIT.java
patch for old LC-436 so that output directory is created.
=> LC-436: create output directory

lucille-plugins/lucille-tika/src/main/java/com/kmwllc/lucille/tika/stage/TextExtractor.java, lucille-plugins/lucille-tika/src/test/java/com/kmwllc/lucille/tika/stage/TextExtractorTest.java
=> LC-528: closing inputStream after parsing

lucille-core/src/main/java/com/kmwllc/lucille/core/Runner.java, lucille-core/src/test/java/com/kmwllc/lucille/core/RunnerTest.java, lucille-core/src/test/resources/RunnerTest/render.conf
- need to create runner tests, but manual testing works so far. Tried normal testing and when giving non existent config path
=> LC-522: add render flag for runner

application-example.conf, lucille-core/src/main/java/com/kmwllc/lucille/message/LocalMessenger.java, lucille-examples/lucille-vector-ingest-example/conf/10M-parquet-pinecone.conf
- increased to 10000
- added some comments
=> LC-542: increase default queue capacity

lucille-plugins/lucille-pinecone/src/main/java/com/kmwllc/lucille/pinecone/indexer/PineconeIndexer.java, lucille-plugins/lucille-pinecone/src/test/java/com/kmwllc/lucille/pinecone/indexer/PineconeIndexerTest.java
- made sure all documents have embeddingFields before converting them to upsertVectors
- made building of upsertVectors only happen if mode has set to "upsert", "update" mode does not use upsertVectors.
=> LC-505: update pineconeIndexer hotfix

application-example.conf, lucille-core/src/main/java/com/kmwllc/lucille/message/HybridIndexerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/HybridWorkerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaIndexerMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaPublisherMessenger.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaUtils.java, lucille-core/src/main/java/com/kmwllc/lucille/message/KafkaWorkerMessenger.java, lucille-core/src/test/java/com/kmwllc/lucille/core/HybridKafkaTest.java, lucille-core/src/test/java/com/kmwllc/lucille/core/KafkaTest.java, lucille-core/src/test/java/com/kmwllc/lucille/message/KafkaMessengerTest.java, lucille-core/src/test/resources/HybridKafkaTest/eventTopic.conf
update the getEventTopicName method to grab a value from the config, if it exists. Updated tests to match
=> LC-553 Support Configurable Event Topic Name

doc/site/content/en/docs/Concepts/connector.md, doc/site/content/en/docs/Concepts/indexer.md, doc/site/content/en/docs/Overview/_index.md
=> Documentation updates

doc/site/content/en/docs/Contribution guidelines/dev_new_stages.md, doc/site/content/en/docs/Contribution guidelines/setup_standards.md
Documentation: add code formatting standards & new stage creation guide
=> LC-560: doc for formatting & stage creation

.github/workflows/release-snapshot.yml, .github/workflows/release-to-sonatype.yml
re update github action versions as publish error was resolved
=> LC-568: re-update github actions

lucille-core/src/main/java/com/kmwllc/lucille/connector/VFSConnector.java
- FileConnector provides all functionality of VFSConnector with better/comparable performance with more options
=> LC-570: deprecate VFSConnector

lucille-examples/lucille-distributed-example/pom.xml, lucille-examples/lucille-file-to-file-example/pom.xml, lucille-examples/lucille-joining-db-connector-example/pom.xml, lucille-examples/lucille-opensearch-ingest-example/pom.xml, lucille-examples/lucille-simple-csv-solr-example/pom.xml, lucille-examples/lucille-vector-ingest-example/pom.xml
=> LC-579 Allows eclipse to build with pinned maven dependency plugin

lucille-core/src/test/java/com/kmwllc/lucille/stage/AddRandomStringTest.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ChunkTextTest.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/HashFieldValueToBucketTest.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/MatchQueryTest.java, lucille-core/src/test/resources/AddRandomStringTest/concatAndNested.conf, lucille-core/src/test/resources/AddRandomStringTest/inputAndRangeNull.conf, lucille-core/src/test/resources/AddRandomStringTest/maxIsNullMinIsNot.conf, lucille-core/src/test/resources/AddRandomStringTest/minIsNullMaxIsNot.conf, lucille-core/src/test/resources/AddRandomStringTest/moreMinThanMax.conf, lucille-core/src/test/resources/ChunkTextTest/customEmptyRegex.conf, lucille-core/src/test/resources/ChunkTextTest/fixedNullSplitLength.conf, lucille-core/src/test/resources/ChunkTextTest/invalidCharacterLimit.conf, lucille-core/src/test/resources/ChunkTextTest/invalidChunksToMerge.conf, lucille-core/src/test/resources/ChunkTextTest/tooMuchOverlap.conf, lucille-core/src/test/resources/ChunkTextTest/tooMuchOverlapPercent.conf, lucille-core/src/test/resources/HashFieldValueToBucketTest/emptyBuckets.conf, lucille-core/src/test/resources/HashFieldValueToBucketTest/emptyDestField.conf, lucille-core/src/test/resources/HashFieldValueToBucketTest/emptyFieldName.conf, lucille-core/src/test/resources/MatchQueryTest/blank_matched_queries.conf, lucille-core/src/test/resources/MatchQueryTest/empty_fields_list.conf, lucille-core/src/test/resources/MatchQueryTest/empty_query_list.conf
The tests primarily ensure that exceptions are thrown when Stages are built with an invalid configuration.
=> LC-481: Small improvements for Stage unit tests

lucille-core/src/main/java/com/kmwllc/lucille/connector/jdbc/DatabaseConnector.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/ChunkText.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/ParseFilePath.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/ParseFloats.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/QueryDatabase.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/TruncateField.java, lucille-core/src/main/java/com/kmwllc/lucille/stage/XPathExtractor.java, lucille-core/src/main/java/com/kmwllc/lucille/util/FileUtils.java, lucille-core/src/main/java/com/kmwllc/lucille/util/JDBCUtils.java, lucille-core/src/main/java/com/kmwllc/lucille/util/SolrUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/util/SolrUtilsTest.java, lucille-plugins/lucille-api/src/test/java/APIIntegrationTest.java, lucille-plugins/lucille-tika/src/main/java/com/kmwllc/lucille/tika/stage/TextExtractor.java
And also removed some unused imports that I encountered along the way.
=> LC-619: Replaced Log4J Imports w/ Slf4J

lucille-parent/pom.xml
for CVEs:
[CVE-2025-24814](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2025-24814)
[CVE-2024-52012](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-52012)
=> LC-645 - upgrade solr and lucene versions

lucille-core/pom.xml, lucille-parent/pom.xml, lucille-plugins/lucille-parquet/pom.xml, lucille-plugins/lucille-tika/pom.xml, lucille-plugins/lucille-weaviate/pom.xml
**org.apache.parquet:parquet-avro** 1.10.2 -> 1.150
--> org.apache.avro:avro  1.10.2 -> 1.11.4
**io.netty:netty-handler**  4.1.117.Final -> 4.1.119.Final
**net.minidev:json-smart** 2.5.0 -> 2.5.2
**org.apache.hadoop:hadoop-common** 3.4.0 -> 3.4.1
--> dnsjava:dnsjava  3.4.0 -> 3.6.1
--> org.apache.commons:commons-configuration2 2.8.0 -> 2.10.0
--> com.nimbusds:nimbus-jose-jwt:jar 9.31 -> 9.37.2
--> org.bouncycastle:bcprov-jdk18on                                    -> 1.78.1
**io.weaviate:client**  4.3.0 → 5.1.2
--> com.nimbusds:nimbus-jose-jwt:jar 9.30.2 -> 9.37.3
**org.apache.tika**  2.9.2 → 2.9.3
--> org.bouncycastle:bcprov-jdk18on  1.77 -> 1.80
**io.dropwizard:dropwizard-logging** 4.0.7 → 4.0.12
--> ch.qos.logback:logback-core 1.4.14 -> 1.5.16
--> ch.qos.logback:logback-classic 1.4.14 …
=> LC-650: Upgrade Critical and High level vulnerabilites

lucille-plugins/lucille-api/Dockerfile, lucille-plugins/lucille-api/README.md, lucille-plugins/lucille-api/pom.xml, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/APIApplication.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/AuthHandler.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/LucilleAPIConfiguration.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/auth/BasicAuthenticator.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/config/AuthConfiguration.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/config/LucilleAPIConfiguration.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/endpoints/LivenessResource.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/endpoints/LucilleResource.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/endpoints/ReadinessResource.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/endpoints/ResponseUtils.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/endpoints/SystemStatsResource.java, lucille-plugins/lucille-api/src/main/java/com/kmwllc/lucille/objects/RunStatus.java
This pull request introduces several updates to the `lucille-api` module, including renaming resources, improving documentation, and enhancing API functionality. The changes aim to standardize the API, improve clarity, and add comprehensive Javadoc comments for maintainability.
* Updated references in the `Dockerfile` to rename the module from `lucille-admin` to `lucille-api` and updated the Dropwizard configuration file from `admin.yml` to `api.yml`. 
* Updated API endpoints in the `README.md` to include a version prefix (`/v1`) for better versioning and clarity.
* Added detailed Javadoc comments across the codebase, including constructors, methods, and class-level descriptions for `APIApplication`, `AuthHandler`, `LucilleAPIConfiguration`, and other key classes. 
* Improved inline …
=> Add documentation and improve code quality for Lucille API components

lucille-plugins/lucille-weaviate/src/main/java/com/kmwllc/lucille/weaviate/indexer/WeaviateIndexer.java, lucille-plugins/lucille-weaviate/src/test/java/com/kmwllc/lucille/weaviate/indexer/WeaviateIndexerTest.java
Unfortunately, I also looked into adding this to Pinecone, but the API doesn't expose enough information to do so.
=> LC-672: Specific Indexer Failures in Weaviate.

lucille-core/src/main/java/com/kmwllc/lucille/stage/AddRandomString.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/AddRandomStringTest.java, lucille-core/src/test/resources/AddRandomStringTest/nestedNoFile.conf, lucille-core/src/test/resources/AddRandomStringTest/nestedWithFile.conf
Also has some other cleanup (JavaDoc + making an existing unit test better).
=> LC-592: is_nested test for AddRandomString

lucille-core/src/main/java/com/kmwllc/lucille/util/FileContentFetcher.java, lucille-core/src/main/java/com/kmwllc/lucille/util/FileUtils.java, lucille-core/src/test/java/com/kmwllc/lucille/util/FileContentFetcherTest.java, lucille-core/src/test/java/com/kmwllc/lucille/util/FileUtilsTest.java, lucille-core/src/test/java/com/kmwllc/lucille/util/LinkedMultiMapTest.java, lucille-core/src/test/java/com/kmwllc/lucille/util/SSLUtilsTest.java, lucille-core/src/test/java/com/kmwllc/lucille/util/SolrUtilsTest.java, lucille-core/src/test/resources/SSLUtilsTest/all.conf
Old Coverage Levels: 91% / 84%
New Coverage Levels: 95% / 95%
Some notes about this PR:
- It includes the changes from LC-597 since that had added tests. 
- In addition to improved test coverage, there are some very small code changes to point out.
1. `FileUtils.isValidURI` - doesn't check whether the scheme is empty. To my understanding, this isn't possible.
2. Resulting from the previous change, `FileContentFetcher` doesn't check if a valid URI has a non-null scheme.
=> LC-620: Improved Test Coverage in Lucille-Core/util

lucille-plugins/lucille-entity-extraction/src/main/java/com/kmwllc/lucille/stage/ApplyOpenNLPNameFinders.java
fix Spec declaration in OpenNLP stage
=> LC-690: build fix

lucille-core/src/main/java/com/kmwllc/lucille/core/fileHandler/CSVFileHandler.java, lucille-core/src/main/java/com/kmwllc/lucille/core/fileHandler/JsonFileHandler.java, lucille-core/src/main/java/com/kmwllc/lucille/core/fileHandler/XMLFileHandler.java
Updated the file handlers to log document paths upon warning, error, and exception. Added some logs where missing.
=> LC-716: Updated file path information in logging

lucille-core/src/main/java/com/kmwllc/lucille/stage/ExtractEntitiesFST.java, lucille-core/src/test/java/com/kmwllc/lucille/stage/ExtractEntitiesFSTTest.java, lucille-core/src/test/resources/ExtractEntitiesFSTTest/configCustomRegexAllPunct.conf, lucille-core/src/test/resources/ExtractEntitiesFSTTest/configCustomWhitespaceOnly.conf, lucille-core/src/test/resources/ExtractEntitiesFSTTest/configDefaultCaseSensitive.conf, lucille-core/src/test/resources/ExtractEntitiesFSTTest/configLowercaseOnly.conf
Defaults to whitespace and punctuation stop characters. Setting the custom regex flag to true defaults to only whitespace.
=> LC-745: Add FST flag for custom regex stop characters
